all:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    checkpoint_mds_host: "192.0.2.10"
    checkpoint_cma_server_ip: "192.0.2.11"
    checkpoint_member_ips:
      - "192.0.2.20"
      - "192.0.2.21"
