---
- import_playbook: ../../../ansible/playbooks/01_validate_activity_plan.yml
  vars: &plan
    activity_plan_file: "{{ example_plan_file }}"
    activity_plan: "{{ lookup('file', example_plan_file) | from_json }}"
    step: install_approved_jhf
    phase: first-member
- import_playbook: ../../../ansible/playbooks/00_precheck.yml
- import_playbook: ../../../ansible/playbooks/07_validate_deployment_agent.yml
  vars: *plan
- import_playbook: ../../../ansible/playbooks/11_capture_cluster_state.yml
- import_playbook: ../../../ansible/playbooks/06_validate_mds_package.yml
  vars: *plan
- import_playbook: ../../../ansible/playbooks/39_api_repository_package.yml
  vars: *plan
- import_playbook: ../../../ansible/playbooks/08_validate_package_prerequisites.yml
  vars: *plan
- import_playbook: ../../../ansible/playbooks/40_api_verify_package.yml
  vars: *plan
- import_playbook: ../../../ansible/playbooks/41_api_execute_package.yml
  vars:
    <<: *plan
    checkpoint_execute_api: "{{ allow_api_changes | default(false) }}"
