---
- import_playbook: ../../../ansible/playbooks/01_validate_activity_plan.yml
  vars:
    activity_plan_file: "{{ example_plan_file }}"
    activity_plan: "{{ lookup('file', example_plan_file) | from_json }}"
